adding contractor_id param to payments
gigwage/slate pull request #4
Opened 2021-03-15 23:31 UTC by geermc4

2021-03-24 23:21 UTC, trappist requested changes

2021-03-24 23:21 UTC, trappist commented on source/includes/_payments.md
> +contractor_id | Filter restults by contractor_id
one line! and it has a typo

2021-03-24 23:31 UTC, geermc4 commented on source/includes/_payments.md
> +contractor_id | Filter restults by contractor_id
fixed

2021-03-25 17:46 UTC, trappist approved these changes

2021-03-25 17:46 UTC, merged